[server]
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
# Balanced dark theme - not too dark, calm and attractive
base = "dark"
primaryColor = "#5D9CEC"  # Soft blue accent
backgroundColor = "#2A2E37"  # Medium dark slate (not too dark)
secondaryBackgroundColor = "#353B48"  # Slightly lighter slate
textColor = "#E4E8F0"  # Soft white text (not harsh)

# Custom theme elements
font = "sans serif"

# UI Element Colors
primaryColorLight = "#78ADEE"  # Lighter accent
primaryColorDark = "#4A7DBD"  # Deeper accent

[theme.components]
# Chat elements
# Adjust message styling
messageTextColor = "#E4E8F0"
messageBorderColor = "#454D5E"
messageBackgroundColor = "#353B48"

# Input field
inputBorderColor = "#454D5E"
inputBackgroundColor = "#3A404E"
inputTextColor = "#E4E8F0"

# Sidebar styling
sidebarBackgroundColor = "#252A33"
sidebarTextColor = "#E4E8F0"
sidebarBorderColor = "#454D5E"

# Button styling
buttonBackgroundColor = "#5D9CEC"
buttonTextColor = "#FFFFFF"

[runner]
packageManager = "pip"
