[server]
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
# Modern dark theme with rich colors
base = "dark"
primaryColor = "#4A90E2"  # Vibrant blue for primary actions
backgroundColor = "#1A1B25"  # Rich dark background
secondaryBackgroundColor = "#252632"  # Slightly lighter for contrast
textColor = "#FFFFFF"  # Crisp white text

# Custom theme elements
font = "sans serif"

# UI Element Colors
primaryColorLight = "#67A7E8"  # Bright blue for hover states
primaryColorDark = "#2E5C99"   # Deep blue for active states

[theme.components]
# Button styling
buttonBorderRadius = "4px"
buttonShadow = "0px 4px 8px rgba(0, 0, 0, 0.2)"
buttonTextColor = "#FFFFFF"

# Input field styling
inputBorderRadius = "4px"
inputBorderColor = "#3A3B47"
inputBackground = "#2A2B35"

# Sidebar styling
sidebarBackgroundColor = "#151620"
sidebarTextColor = "#E0E0E0"
sidebarBorderColor = "#2A2B35"

[runner]
packageManager = "pip"
