[server]
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
# Soft, eye-friendly modern theme
base = "light"
primaryColor = "#7C83FD"  # Soft lavender-blue
backgroundColor = "#F0F2F6"  # Very soft gray-blue
secondaryBackgroundColor = "#E2E6F0"  # Slightly deeper soft blue-gray
textColor = "#424B5A"  # Soft navy text

# Custom theme elements
font = "sans serif"

# UI Element Colors
primaryColorLight = "#96A1FD"  # Lighter lavender
primaryColorDark = "#6369CB"  # Deeper lavender

[theme.components]
# Chat elements
# Adjust message styling
messageTextColor = "#424B5A"
messageBorderColor = "#D8DEE9"
messageBackgroundColor = "#FFFFFF"

# Input field
inputBorderColor = "#D8DEE9"
inputBackgroundColor = "#FFFFFF"
inputTextColor = "#424B5A"

# Sidebar styling
sidebarBackgroundColor = "#E8ECF4"
sidebarTextColor = "#424B5A"
sidebarBorderColor = "#D8DEE9"

# Button styling
buttonBackgroundColor = "#7C83FD"
buttonTextColor = "#FFFFFF"

[runner]
packageManager = "pip"
