[server]
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#4169E1"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"


[runner]
# Use pip as the package manager to avoid issues with deprecated plugins
packageManager = "pip"

