[server]
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
# Glassmorphism theme with gradient effects
base = "light"
primaryColor = "#7C3AED"  # Vibrant purple
backgroundColor = "#F0F4FF"  # Soft blue-white
secondaryBackgroundColor = "rgba(255, 255, 255, 0.95)"  # Translucent white
textColor = "#1E293B"  # Slate blue text

# Typography
font = "sans serif"

# UI Elements with glass effect
primaryColorLight = "#9F67FF"  # Light purple for gradients
primaryColorDark = "#6D28D9"   # Deep purple for emphasis

[theme.components]
# Modern button styling
buttonBorderRadius = "12px"
buttonShadow = "0 8px 32px 0 rgba(31, 38, 135, 0.37)"
buttonTextColor = "#FFFFFF"
buttonBackgroundColor = "rgba(124, 58, 237, 0.9)"  # Semi-transparent purple

# Sleek input styling
inputBorderRadius = "12px"
inputBorderColor = "rgba(124, 58, 237, 0.3)"
inputBackground = "rgba(255, 255, 255, 0.8)"

# Glass effect sidebar
sidebarBackgroundColor = "rgba(255, 255, 255, 0.85)"
sidebarTextColor = "#1E293B"
sidebarBorderColor = "rgba(124, 58, 237, 0.2)"
sidebarShadow = "0 8px 32px 0 rgba(31, 38, 135, 0.37)"

# Card and container styling
containerBorderRadius = "16px"
containerShadow = "0 8px 32px 0 rgba(31, 38, 135, 0.15)"
containerBackgroundColor = "rgba(255, 255, 255, 0.9)"

# Accent colors for visual hierarchy
accentColorLight = "#F0EEFF"  # Very light purple
accentColorMedium = "#DDD6FE"  # Medium purple tint
accentColorDark = "#7C3AED"  # Deep purple

[runner]
packageManager = "pip"
