[server]
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
# Balanced professional theme
base = "light"
primaryColor = "#3B7EA1"  # Calm blue-teal
backgroundColor = "#F5F7FA"  # Soft off-white
secondaryBackgroundColor = "#E9EEF2"  # Light blue-gray
textColor = "#2C3E50"  # Deep blue-gray text

# Custom theme elements
font = "sans serif"

# UI Element Colors
primaryColorLight = "#5499BD"  # Lighter accent
primaryColorDark = "#2C6384"  # Deeper accent

[theme.components]
# Chat elements
# Adjust message styling
messageTextColor = "#2C3E50"
messageBorderColor = "#D1DCE5"
messageBackgroundColor = "#FFFFFF"

# Input field
inputBorderColor = "#C0CFD9"
inputBackgroundColor = "#FFFFFF"
inputTextColor = "#2C3E50"

# Sidebar styling
sidebarBackgroundColor = "#EDF2F7"
sidebarTextColor = "#2C3E50"
sidebarBorderColor = "#D1DCE5"

# Button styling
buttonBackgroundColor = "#3B7EA1"
buttonTextColor = "#FFFFFF"

[runner]
packageManager = "pip"
