[server]
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#0066CC"  # Strong professional blue
backgroundColor = "#F8FAFF"  # Very light blue tint
secondaryBackgroundColor = "#E8F0FF"  # Slightly darker blue tint
textColor = "#091133"  # Deep navy text

# Fonts and typography
font = "sans serif"

# UI Elements
primaryColorLight = "#3385D6"  # Lighter accent
primaryColorDark = "#004C99"   # Darker accent

[runner]
packageManager = "pip"
