[server]
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
# Minimalistic Sindhi-inspired theme
base = "light"
primaryColor = "#B84B1C"  # Warm terracotta (inspired by Ajrak)
backgroundColor = "#FFF9F5"  # Soft cream (like handmade paper)
secondaryBackgroundColor = "#F5EDE6"  # Warm beige (like clay pottery)
textColor = "#2C1810"  # Deep brown (like walnut wood)

# Typography
font = "sans serif"

# Accent colors (from traditional Sindhi textiles)
primaryColorLight = "#C66D47"  # Lighter terracotta
primaryColorDark = "#8C3816"   # Deep maroon

[theme.components]
# Minimal, elegant styling
buttonBorderRadius = "2px"  # Subtle rounded corners
buttonShadow = "none"  # Flat design
buttonTextColor = "#FFFFFF"

# Input fields with subtle borders
inputBorderRadius = "2px"
inputBorderColor = "#D4C0B3"  # Soft brown border
inputBackground = "#FFFFFF"

# Sidebar with cultural touch
sidebarBackgroundColor = "#F5EDE6"  # Warm beige
sidebarTextColor = "#2C1810"  # Deep brown text
sidebarBorderColor = "#E6D5C9"  # Soft border

[runner]
packageManager = "pip"
