[server]
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
# Modern trendy dark theme with gradient feel
base = "dark"
primaryColor = "#6C5CE7"  # Vibrant purple
backgroundColor = "#1E1E2E"  # Deep space blue-black
secondaryBackgroundColor = "#2D2D44"  # Slightly lighter space blue
textColor = "#F8F9FA"  # Crisp white

# Custom theme elements
font = "sans serif"

# UI Element Colors
primaryColorLight = "#8075E5"  # Lighter purple
primaryColorDark = "#5546C5"  # Deeper purple

[theme.components]
# Chat elements
# Adjust message styling
messageTextColor = "#F8F9FA"
messageBorderColor = "#3D3D5C"
messageBackgroundColor = "#2D2D44"

# Input field
inputBorderColor = "#3D3D5C"
inputBackgroundColor = "#2D2D44"
inputTextColor = "#F8F9FA"

# Sidebar styling
sidebarBackgroundColor = "#191927"
sidebarTextColor = "#F8F9FA"
sidebarBorderColor = "#3D3D5C"

# Button styling
buttonBackgroundColor = "#6C5CE7"
buttonTextColor = "#FFFFFF"

[runner]
packageManager = "pip"
