[server]
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#2E54FF"  # Modern blue - professional and trustworthy
backgroundColor = "#FFFFFF"  # Clean white background
secondaryBackgroundColor = "#F6F8FF"  # Soft blue tint for depth
textColor = "#1E1E1E"  # Near-black for better readability

# Custom theme options
font = "sans serif"

# These will create subtle gradients and shadows
primaryColorLight = "#4C6FFF"  # Lighter shade of primary blue
primaryColorDark = "#1C3EEB"   # Darker shade of primary blue

[runner]
packageManager = "pip"
