[server]
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
# Soft dark theme - gentle on eyes
base = "dark"
primaryColor = "#7B68EE"  # Medium slate blue - soft yet vibrant
backgroundColor = "#292D3E"  # Soft navy background (not too dark)
secondaryBackgroundColor = "#373E5C"  # Slightly lighter navy
textColor = "#E0E7FF"  # Soft blue-white text

# Custom theme elements
font = "sans serif"

# UI Element Colors
primaryColorLight = "#9C8FFF"  # Lighter slate blue
primaryColorDark = "#6A5ACD"  # Deeper slate blue

[theme.components]
# Chat elements
# Adjust message styling
messageTextColor = "#E0E7FF"
messageBorderColor = "#4A5377"
messageBackgroundColor = "#373E5C"

# Input field
inputBorderColor = "#4A5377"
inputBackgroundColor = "#373E5C"
inputTextColor = "#E0E7FF"

# Sidebar styling
sidebarBackgroundColor = "#242837"
sidebarTextColor = "#E0E7FF"
sidebarBorderColor = "#4A5377"

# Button styling
buttonBackgroundColor = "#7B68EE"
buttonTextColor = "#FFFFFF"

[runner]
packageManager = "pip"
