[server]
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
# Modern dark theme inspired by OKYAI
base = "dark"
primaryColor = "#9C5FFF"  # Vibrant purple
backgroundColor = "#1E1F2A"  # Deep charcoal
secondaryBackgroundColor = "#2D2E3D"  # Slightly lighter charcoal
textColor = "#FFFFFF"  # Crisp white

# Custom theme elements
font = "sans serif"

# UI Element Colors
primaryColorLight = "#B27CFF"  # Lighter purple
primaryColorDark = "#8442E5"  # Deeper purple

[theme.components]
# Chat elements
# Adjust message styling
messageTextColor = "#FFFFFF"
messageBorderColor = "#3D3E4D"
messageBackgroundColor = "#2D2E3D"

# Input field
inputBorderColor = "#3D3E4D"
inputBackgroundColor = "#2D2E3D"
inputTextColor = "#FFFFFF"

# Sidebar styling
sidebarBackgroundColor = "#18191F"
sidebarTextColor = "#FFFFFF"
sidebarBorderColor = "#3D3E4D"

# Button styling
buttonBackgroundColor = "#9C5FFF"
buttonTextColor = "#FFFFFF"

[runner]
packageManager = "pip"
