[server]
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#FF4B4B"  # Emergency red color
backgroundColor = "#0E1117"  # Dark background
secondaryBackgroundColor = "#262730"  # Slightly lighter dark
textColor = "#FAFAFA"  # Light text for readability
font = "sans serif"

[runner]
# Use pip as the package manager to avoid issues with deprecated plugins
packageManager = "pip"
