[server]
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
# Modern glass effect with gradient background
base = "dark"
primaryColor = "#9D4EDD"  # Rich purple
backgroundColor = "#0A1128"  # Deep navy background
secondaryBackgroundColor = "rgba(41, 50, 100, 0.3)"  # Translucent navy
textColor = "#E2E8F0"  # Soft white text

# Typography
font = "sans serif"

# UI Elements with glass effect
primaryColorLight = "#C77DFF"  # Light purple for hover
primaryColorDark = "#7B2CBF"   # Deep purple for active states

[theme.components]
# Glassy button styling
buttonBorderRadius = "12px"
buttonShadow = "0 8px 32px 0 rgba(157, 78, 221, 0.4)"
buttonTextColor = "#FFFFFF"
buttonBackgroundColor = "rgba(157, 78, 221, 0.2)"  # Translucent purple

# Modern input styling
inputBorderRadius = "12px"
inputBorderColor = "rgba(157, 78, 221, 0.3)"
inputBackground = "rgba(41, 50, 100, 0.2)"

# Glass effect sidebar
sidebarBackgroundColor = "rgba(10, 17, 40, 0.7)"
sidebarTextColor = "#E2E8F0"
sidebarBorderColor = "rgba(157, 78, 221, 0.2)"
sidebarShadow = "0 8px 32px 0 rgba(157, 78, 221, 0.2)"

# Card and container styling
containerBorderRadius = "16px"
containerShadow = "0 8px 32px 0 rgba(157, 78, 221, 0.15)"
containerBackgroundColor = "rgba(41, 50, 100, 0.3)"

# Accent colors for depth
accentColorLight = "rgba(157, 78, 221, 0.1)"  # Very light purple
accentColorMedium = "rgba(157, 78, 221, 0.3)"  # Medium purple
accentColorDark = "rgba(157, 78, 221, 0.5)"  # Deep purple

[runner]
packageManager = "pip"
